# Dataset preparation

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("dataset befor join/heart.csv")
df1=pd.read_csv("dataset befor join/Heart diseases prediction.csv")
df2=pd.read_csv("dataset befor join/heart_cleveland_upload.csv")
df3=pd.read_csv("dataset befor join/heart_disease.csv")
df4=pd.read_csv("dataset befor join/heart1.csv")
df5=pd.read_csv("dataset befor join/heart2.csv")
df5.shape

(270, 14)

In [3]:
df.columns=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [4]:
df1.columns=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

In [5]:
df2.columns=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

In [6]:
df3.columns=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

In [7]:
df4.columns=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

In [8]:
df5.columns=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

In [9]:
df.target.unique()

array([0, 1], dtype=int64)

In [10]:
df1.target.unique()

array([1, 0], dtype=int64)

In [11]:
df2.target.unique()

array([0, 1], dtype=int64)

In [12]:
df3.target.unique()

array([0, 1], dtype=int64)

In [13]:
df4.target.unique()

array([1, 0], dtype=int64)

In [14]:
df5=df5.replace({'target':{2:1,1:0}})

In [15]:
df5.target.unique()

array([1, 0], dtype=int64)

In [16]:
data=pd.concat([df,df1,df2,df3,df4,df5], ignore_index=True)
data.shape

(2729, 14)

In [17]:
data.target.unique()

array([0, 1], dtype=int64)

In [18]:
data['target']

0       0
1       0
2       0
3       0
4       0
       ..
2724    0
2725    0
2726    0
2727    0
2728    1
Name: target, Length: 2729, dtype: int64

In [19]:
# checking null record
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [20]:
# duplicate checking, if it exist output is true else false  
data.duplicated().any()

True

In [21]:
# removing duplicates and checking size of data
data=data.drop_duplicates(subset=None, keep='first', inplace=False,ignore_index=True)
data.shape

(869, 14)

In [22]:
data.target.unique()

array([0, 1], dtype=int64)

In [23]:
# checkng the distribution of target variable
data["target"].value_counts()

0    448
1    421
Name: target, dtype: int64

# second draft(entire attribute checking) 

### Importing model buliding libraries 

In [24]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [25]:
ds1=pd.read_csv("dataset befor join/heart.csv")
ds2=pd.read_csv("dataset befor join/Heart diseases prediction.csv")
ds3=pd.read_csv("dataset befor join/heart_cleveland_upload.csv")
ds4=pd.read_csv("dataset befor join/heart_disease.csv")
ds5=pd.read_csv("dataset befor join/heart1.csv")
ds6=pd.read_csv("dataset befor join/heart2.csv")

In [26]:
ds1.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [27]:
ds1["thal"].unique()

array([3, 2, 1, 0], dtype=int64)

In [28]:
#thal:this dataset array([3, 2, 1], dtype=int64) and other dataset array([3, 2, 1, 0], dtype=int64)
#
ds2["thal"].unique()

array([3, 2, 1], dtype=int64)

In [29]:
#ca:this dataset array([1, 2, 0, 3],dtype=int64) and other dataset array([1, 0, 3, 4, 2],dtype=int64)
#
ds3["thal"].unique()

array([0, 2, 1], dtype=int64)

In [30]:
ds4["thal"].unique()

array([2, 3, 1, 0], dtype=int64)

In [31]:
ds5["thal"].unique()

array([1, 2, 3, 0], dtype=int64)

In [32]:
ds6.head()

Age  Sex  Chest Pain type  Resting Blood pressure  \
0   70    1                4                     130   
1   67    0                3                     115   
2   57    1                2                     124   
3   64    1                4                     128   
4   74    0                2                     120   

   Serum Cholestoral in mg/dl  Fasting Blood sugar > 120 mg/dl  \
0                         322                                0   
1                         564                                0   
2                         261                                0   
3                         263                                0   
4                         269                                0   

   Resting Electrocardiographic results  Max heart rate achieved  \
0                                     2                      109   
1                                     2                      160   
2                                     0                      141   
3                                     0                      105   
4                                     2                      121   

   Exercise induced angina  Oldpeak  Slope of the peak exercise ST segment  \
0                        0      2.4                                      2   
1                        0      1.6                                      2   
2                        0      0.3                                      1   
3                        1      0.2                                      2   
4                        1      0.2                                      1   

   No of major vessels  Thal  Presence  
0                    3     3         2  
1                    0     7         1  
2                    0     7         2  
3                    1     7         1  
4                    1     3         1

In [33]:
#chest pain type value varry("differ") other 0,1,2,3 but 1,2,3,4 
#
#slope:this dataset array([2, 1, 3], dtype=int64) and other dataset array([0, 2, 1], dtype=int64)
#ca:this dataset array([3, 0, 1, 2], dtype=int64)and other dataset array([0, 2, 1, 3, 4], dtype=int64)
#thal:this dataset array([3, 7, 6], dtype=int64) and other dataset array([1, 2, 3, 0], dtype=int64)
#
ds6["Thal"].unique()

array([3, 7, 6], dtype=int64)

In [34]:
# from above datasets three datasets are the same attributes value
# these are ds1,ds4,ds5, so i select this datasets

print("ds1:",ds1.shape,"ds4:",ds4.shape,"ds5:",ds5.shape)

ds1: (1025, 14) ds4: (622, 14) ds5: (303, 14)


In [35]:
print("ds1:",ds1.columns)
print("ds4:",ds4.columns)
print("ds5:",ds5.columns)

ds1: Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')
ds4: Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')
ds5: Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')


In [36]:
ds5.isnull().sum()
ds5.duplicated().any()

True

In [37]:
ds1=ds1.drop_duplicates(subset=None, keep='first', inplace=False,ignore_index=True)
ds1.shape

(302, 14)

In [38]:
ds4=ds4.drop_duplicates(subset=None, keep='first', inplace=False,ignore_index=True)
ds4.shape

(295, 14)

In [39]:
ds5=ds5.drop_duplicates(subset=None, keep='first', inplace=False,ignore_index=True)
ds5.shape

(302, 14)

In [40]:
# concatenating datasets(joining d/t datasets) 
hds=pd.concat([ds1,ds4,ds5], ignore_index=True)
hds.shape

(899, 14)

In [41]:

#checking duplicate after concatention  
hds=hds.drop_duplicates(subset=None, keep='first', inplace=False,ignore_index=True)
print("after joining all datasets")
hds.shape

after joining all datasets


(302, 14)

In [42]:
# saving datasets after removing duplicates in compressed (zip) format

# compression_opts=dict(method='zip',archive_name='Heart_Disease_Prediction_Dataset.csv')
# hds.to_csv('heart_disease_prediction.zip',index=False,compression=compression_opts)

In [45]:
# save datasets in csv format
hds.to_csv(r'C:\Users\Amexo\Documents\AI\heart dataset after prep\heart_dataset.csv',index=False)

In [46]:
hds.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [47]:
hds['ca'].unique()

array([2, 0, 1, 3, 4], dtype=int64)

In [48]:
hds = hds[hds['ca'] < 4] #drop the wrong ca values
hds = hds[hds['thal'] > 0] # drop the wong thal value
hds.shape

(296, 14)

In [49]:
hds['thal'].unique()

array([3, 2, 1], dtype=int64)

### collected kaggle data

In [50]:
hds.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [51]:
hds.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [52]:
hds["slope"].unique()

array([2, 0, 1], dtype=int64)

In [53]:
hds["ca"].unique()

array([2, 0, 1, 3], dtype=int64)

In [54]:
hds["thal"].unique()

array([3, 2, 1], dtype=int64)

### dataset from UCI 

In [55]:
uci_data=pd.read_csv("uci_dataset/processed.cleveland1.data")

In [56]:
uci_data.shape

(303, 14)

In [57]:
uci_data.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca thal   num  
0    3.0  0.0  6.0     0  
1    2.0  3.0  3.0     2  
2    2.0  2.0  7.0     1  
3    3.0  0.0  3.0     0  
4    1.0  0.0  3.0     0

In [58]:
uci_data.columns=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

In [59]:
uci_data.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca thal  target  
0    3.0  0.0  6.0       0  
1    2.0  3.0  3.0       2  
2    2.0  2.0  7.0       1  
3    3.0  0.0  3.0       0  
4    1.0  0.0  3.0       0

In [60]:
# uci_heart.isna().sum()
uci_data["target"].unique()

array([0, 2, 1, 3, 4], dtype=int64)

In [61]:
uci_data["slope"].unique()

array([3., 2., 1.])

In [62]:
# 51 thal: 3 = normal; 6 = fixed defect; 7 = reversable defect
uci_data["thal"].unique()

array(['6.0', '3.0', '7.0', '?'], dtype=object)

In [63]:

# Experiments with the Cleveland database have concentrated on simply attempting 
# to distinguish presence (values 1,2,3,4) and absence (value 0)

# let us convert target value of (2,3,4) into 1 

uci_data["target"].replace({2:1, 3:1, 4:1}, inplace=True)

    uci_data["cp"].replace({1:0, 2:1, 3:2,4:3}, inplace=True)
uci_data["slope"].replace({1:0, 2:1, 3:2}, inplace=True)
uci_data["thal"].replace({3.0:0, 6.0:1, 7.0:2}, inplace=True)
uci_data["thal"].unique()

IndentationError: unexpected indent (1216876491.py, line 8)

In [64]:
uci_data["cp"].unique()
uci_data["target"].unique()


array([0, 2, 1, 3, 4], dtype=int64)

In [65]:
kaggle_data=hds

In [66]:
heart_dataset=pd.concat([uci_data,kaggle_data], ignore_index=True)
heart_dataset.shape

(599, 14)

In [67]:
#checking duplicate after concatention  
heart_dataset=heart_dataset.drop_duplicates(subset=None, keep='first', inplace=False,ignore_index=True)
heart_dataset.shape

(599, 14)

In [68]:
heart_dataset.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca thal  target  
0    3.0  0.0  6.0       0  
1    2.0  3.0  3.0       2  
2    2.0  2.0  7.0       1  
3    3.0  0.0  3.0       0  
4    1.0  0.0  3.0       0

In [69]:
# checking null value
data=heart_dataset
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [70]:
# checking ? character
data = data[(data != '?').all(axis=1)] 
data = data[(data != '?.').all(axis=1)] 
data = data[(data != '?     ').all(axis=1)] 
data = data[(data != '? ').all(axis=1)]

In [76]:
# save datasets in csv format
data.to_csv(r'C:\Users\Amexo\Documents\AI\heart dataset after prep\heart_disease_prediction.csv',index=False)

In [77]:
data=pd.read_csv("heart dataset after prep/heart_disease_prediction.csv")

In [78]:
data.shape


(593, 14)

In [79]:
data.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [80]:
data.thal.unique()

array([6., 3., 7., 2., 1.])